# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

def shared_pods
    pod 'MidtransCoreKit', '~> 1.15.0'
    pod 'MidtransKit', '~> 1.15.0'
end

target 'MidtransModule' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MidtransModule
  shared_pods

end
